# Generated by Django 2.0.6 on 2021-03-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=32)),
                ('sex', models.BooleanField(default=True, verbose_name='True为男')),
                ('phone', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
